#ifndef MENU_H
#define MENU_H 

#include "common.h"

// FUNCTION MENU
void MENU_AWAL();
void SUB_MENU_SLL();
void SUB_MENU_DLL();
void SUB_MENU_ARR();

// FUNCTION SUB MENU
void MENU_TITLE_CREATE_BUKU();
void MENU_INPUT_STOKBUKU();
void MENU_EDIT_PILIHBUKU();
void MENU_EDIT_JUDULBUKU();
void MENU_EDIT_STOKBUKU();
void MENU_DELETE_BUKU();
void MENU_INPUT_NAMA_ANGGOTA();
void MENU_INPUT_LEVEL_ANGGOTA();
void MENU_EDIT_NAMA_ANGGOTA();
void MENU_EDIT_LEVEL_ANGGOTA();
void MENU_DELETE_ANGGOTA();
void MENU_PILIH_BUKU();
void MENU_KEMBALIKAN_BUKU();
void TAMPILKAN_VISUAL();

// Other 
void MENU_PILIH_ORANG();
void MENU_WARNING();

#endif 